<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-RawannyCanela/blob/main/AtividadePr%C3%A1tica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Treino de NumPy — 42 exercícios hands-on

##**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
##**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.

import numpy as np
rng = np.random.default_rng(42)

## Fáceis (24)

### 1. Vetor de zeros  _(fácil)_
## Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

v1 = np.zeros(10)
v1_dtype_shape = (v1.dtype, v1.shape)
print("1) v1:", v1)


### 2. Vetor de uns  _(fácil)_
##Crie um array 1D com 10 uns e transforme-o em float64.

v2 = np.ones(10, dtype=np.float64)
print("2) v2:", v2)


### 3. Sequência 0–9  _(fácil)_
##Crie um array com os inteiros de 0 a 9 (inclusive).

v3 = np.arange(10)
print("3) v3:", v3)


### 4. Matriz 3×3 com 0…8  _(fácil)_
##Crie um array 3×3 com os valores 0…8 (reshape).

m4 = np.arange(9).reshape(3,3)
print("4) m4:\n", m4)


### 5. Índices não zero  _(fácil)_
##Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

v = np.array([1,2,0,0,4,0])
idx5 = np.nonzero(v)[0]
print("5) idx5 (não zero):", idx5)


### 6. Linspace  _(fácil)_
##Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

v6 = np.linspace(0, 1, 12)
print("6) v6:", v6)


### 7. Identidade 5×5  _(fácil)_
##Crie uma matriz identidade de ordem 5.

I5 = np.eye(5)
print("7) I5:\n", I5)


### 8. Aleatórios 3×3×3  _(fácil)_
##Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

m8 = rng.random((3,3,3))
print("8) m8 (3x3x3):\n", m8)


### 9. Min/Max  _(fácil)_
## Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

m9 = rng.random((10,10))
m9_min, m9_max = m9.min(), m9.max()
print("9) m9 min/max:", m9_min, m9_max)


### 10. Padronização 1D  _(fácil)_
##Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

x = np.array([1,2,3,4,5], dtype=float)
x10 = (x - x.mean()) / x.std(ddof=0)
print("10) x10 (z-score):", x10)


### 11. Conversão de tipos  _(fácil)_
##Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

a11 = np.array([1,2,3], dtype=np.int32)
a11_f32 = a11.astype(np.float32)
a11_i64 = a11_f32.astype(np.int64)
print("11) a11:", a11, "\n    a11_f32:", a11_f32, "\n    a11_i64:", a11_i64)


### 12. Clipping  _(fácil)_
##Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

a12 = np.array([2,5,7,1,9])
a12_clipped = np.clip(a12, 0, 5)
print("12) a12_clipped:", a12_clipped)


### 13. Inversão  _(fácil)_
##Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

v13 = np.arange(10)
v13_inv = np.flip(v13)
print("13) v13:", v13, "\n    v13_inv:", v13_inv)


### 14. Empilhamento  _(fácil)_
## Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

a14 = np.array([1,2,3])
b14 = np.array([4,5,6])
h14 = np.hstack([a14, b14])
v14 = np.vstack([a14, b14])
print("14) h14:", h14, "\n    v14:\n", v14)


### 15. Diagonal  _(fácil)_
## Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

m15 = np.diag(np.full(4, 5.0))
print("15) m15:\n", m15)


### 16. Somas por eixo  _(fácil)_
##Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

A16 = np.arange(12).reshape(3,4)
sum_rows16 = A16.sum(axis=1)
sum_cols16 = A16.sum(axis=0)
print("16) A16:\n", A16, "\n    sum_rows16:", sum_rows16, "\n    sum_cols16:", sum_cols16)


### 17. Frequências inteiras  _(fácil)_
## Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

x17 = rng.integers(0, 10, size=100)
freq17 = np.bincount(x17, minlength=10)
print("17) x17 (100 ints):", x17, "\n    freq17:", freq17)


### 18. Slicing com passo  _(fácil)_
##Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

v18 = np.arange(20)
v18_sel = v18[1::3]
print("18) v18:", v18, "\n    v18_sel:", v18_sel)


### 19. Máscara booleana  _(fácil)_
##Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

v19 = np.arange(20)
mask19 = (v19 % 2 == 0)
v19_pares = v19[mask19]
print("19) v19:", v19, "\n    mask19:", mask19, "\n    v19_pares:", v19_pares)


### 20. Lista de listas → array  _(fácil)_
##Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

L20 = [[1,2,3],[4,5,6]]
A20 = np.array(L20)
shape20, dtype20 = A20.shape, A20.dtype
print("20) A20:\n", A20, "\n    shape/dtype:", shape20, dtype20)


### 21. Datas básicas  _(fácil)_
##Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

dates21 = np.arange(np.datetime64('2025-01-01'), np.datetime64('2025-01-08'))
print("21) dates21:", dates21)


### 22. Centralizar colunas  _(fácil)_
##Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

A22 = np.array([[1.,2.,3.],[4.,5.,6.]])
A22_centered = A22 - A22.mean(axis=0, keepdims=True)
print("22) A22:\n", A22, "\n    A22_centered:\n", A22_centered)


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_
##Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

a23 = np.array([1,2,3])
b23 = np.array([4,5,6])
elem23 = a23 * b23
dot23 = a23 @ b23
print("23) elem23:", elem23, " dot23:", dot23)


### 24. Troca de colunas  _(fácil)_
## Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

A24 = np.arange(12).reshape(3,4)
tmp = A24[:, 0].copy()
A24[:, 0] = A24[:, 2]
A24[:, 2] = tmp
print("24) A24 (colunas 0 e 2 trocadas):\n", A24)




## Médios (12)

### 25. Flatten vs. ravel  _(médio)_
##Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

A25 = np.arange(6).reshape(2,3)
flat25 = A25.flatten()
rav25 = A25.ravel()
rav25[0] = -1
A25_after = A25.copy()
print("25) A25:\n", A25, "\n    flat25 (cópia):", flat25, "\n    rav25 (view):", rav25, "\n    A25_after (snap):\n", A25_after)


# 26. Tabuleiro 8 por 8  (médio)
# Crie uma matriz 8 por 8 com padrão de tabuleiro (0 e 1 alternados).

m26 = (np.indices((8, 8)).sum(axis=0) % 2).astype(int)
print("26) m26 (tabuleiro 8x8):\n", m26)


### 27. np.where condicional  _(médio)_
##Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

x27 = np.arange(-5,6)
y27 = np.where(x27 < 0, 0, x27)
print("27) x27:", x27, "\n    y27 (negativos->0):", y27)


### 28. Precisão de média  _(médio)_
##Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

x28 = rng.random(1_000_000)
mean28 = x28.mean()
err28 = abs(mean28 - 0.5)
print("28) mean28:", mean28, " | err28:", err28)


### 29. Produto cartesiano (broadcasting)  _(médio)_
##Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

a29 = np.array([1,2,3])[:, None]
b29 = np.array([10,20,30,40])[None, :]
M29 = a29 + b29
print("29) M29 (a+b):\n", M29)


### 30. Convolução 1D simples  _(médio)_
##Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

from numpy.lib.stride_tricks import sliding_window_view
s30 = np.array([1,2,3,4,5,6], dtype=float)
k30 = np.array([1,0,-1], dtype=float)
windows30 = sliding_window_view(s30, k30.size)  # shape (N-k+1, k)
conv30 = (windows30 * np.flip(k30)).sum(axis=1)
print("30) windows30:\n", windows30, "\n    conv30:", conv30)


### 31. Normalização min–max por coluna  _(médio)_
##Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

A31 = rng.normal(size=(5,4))
min31 = A31.min(axis=0, keepdims=True)
max31 = A31.max(axis=0, keepdims=True)
range31 = max31 - min31
A31_norm = (A31 - min31) / np.where(range31 == 0, 1, range31)
print("31) A31:\n", A31, "\n    A31_norm [0,1] por coluna:\n", A31_norm)


### 32. Ordenar por coluna  _(médio)_
##Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.

A32 = np.array([[3,9],[1,4],[2,5]])
A32_sorted = A32[np.argsort(A32[:,1])]
print("32) A32_sorted por 2ª coluna:\n", A32_sorted)


### 33. Únicos + contagens + primeira ocorrência  _(médio)_
##Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

x33 = np.array([3,1,2,3,2,3,1])
vals33, idx_first33, counts33 = np.unique(x33, return_index=True, return_counts=True)
first_occurrence33 = idx_first33
print("33) vals33:", vals33, " counts33:", counts33, " first_occurrence33:", first_occurrence33)


### 34. Matriz de distâncias 2D  _(médio)_
##Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

P34 = rng.normal(size=(5,2))
diffs34 = P34[:, None, :] - P34[None, :, :]
D34 = np.sqrt((diffs34**2).sum(axis=2))
print("34) P34:\n", P34, "\n    D34 (distâncias):\n", D34)


### 35. Covariância e correlação  _(médio)_
##Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

X35 = rng.normal(size=(1000,3))
cov35 = np.cov(X35, rowvar=False, ddof=1)
corr35 = np.corrcoef(X35, rowvar=False)
print("35) cov35:\n", cov35, "\n    corr35:\n", corr35)


### 36. One-hot encoding  _(médio)_
##Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

y36 = np.array([2,0,1,2])
n_classes36 = y36.max() + 1
onehot36 = np.eye(n_classes36, dtype=int)[y36]
print("36) y36:", y36, "\n    onehot36:\n", onehot36)

### 37. k-means 2D (NumPy puro)  (difícil)
##Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

X37 = rng.normal(size=(200,2))
centroids37 = X37[rng.choice(len(X37), size=3, replace=False)]
for _ in range(10):
    dists = ((X37[:, None, :] - centroids37[None, :, :])**2).sum(axis=2)
    labels = dists.argmin(axis=1)
    new_centroids = np.array([X37[labels==k].mean(axis=0) if np.any(labels==k) else centroids37[k]
                              for k in range(3)])
    centroids37 = new_centroids
labels37 = labels.copy()
print("37) centroids37:\n", centroids37)
u37, c37 = np.unique(labels37, return_counts=True)
print("    cluster sizes:", dict(zip(u37.tolist(), c37.tolist())))


### 38. PCA básica (autovetores)  (difícil)
##Implemente PCA 2D→1D: centralize X (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.

X38 = rng.normal(size=(300,2))
X38c = X38 - X38.mean(axis=0, keepdims=True)
C38 = (X38c.T @ X38c) / (X38c.shape[0] - 1)
eigvals38, eigvecs38 = np.linalg.eigh(C38)
w1 = eigvecs38[:, -1]
z38 = X38c @ w1
X38_recon = np.outer(z38, w1) + X38.mean(axis=0, keepdims=True)
print("38) C38:\n", C38)
print("    eigvals38:", eigvals38)
print("    w1:", w1)
print("    z38[:5]:", z38[:5])
print("    X38_recon[:5]:\n", X38_recon[:5])


### 39. Convolução 2D (im2col)  (difícil)
##Implemente convolução 2D 'valid' de uma imagem I por um kernel K usando sliding_window_view para gerar blocos e multiplicação matricial.

I39 = rng.normal(size=(8,8))
K39 = np.array([[1,0,-1],
                [1,0,-1],
                [1,0,-1]], dtype=float)
win39 = sliding_window_view(I39, K39.shape)
Hout, Wout = win39.shape[:2]
cols39 = win39.reshape(Hout*Wout, -1)
conv39 = (cols39 @ K39[::-1, ::-1].ravel()).reshape(Hout, Wout)
print("39) conv39 (valid) shape:", (Hout, Wout))
print(conv39)


### 40. Sistemas lineares e resíduo  (difícil)
##Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva Ax=b com np.linalg.solve. Compute o resíduo relativo ||Ax−b||/||b|| e cond(A).

Q,_ = np.linalg.qr(rng.normal(size=(100,100)))
D = np.diag(np.linspace(1.0, 10.0, 100))
A40 = Q @ D @ Q.T
b40 = rng.normal(size=100)
x40 = np.linalg.solve(A40, b40)
res40 = np.linalg.norm(A40@x40 - b40) / np.linalg.norm(b40)
cond40 = np.linalg.cond(A40)
print("40) resíduo relativo:", res40)
print("    cond(A40):", cond40)


### 41. Regressão linear (OLS) com NumPy  (difícil)
##Dado X (N×d) e y, calcule os coeficientes OLS usando np.linalg.lstsq e avalie RMSE no treino.

N, d = 300, 5
X41 = rng.normal(size=(N,d))
beta_true = rng.normal(size=d)
y41 = X41 @ beta_true + rng.normal(scale=0.5, size=N)
beta_hat, *_ = np.linalg.lstsq(X41, y41, rcond=None)
pred41 = X41 @ beta_hat
rmse41 = np.sqrt(np.mean((pred41 - y41)**2))
print("41) beta_true:", beta_true)
print("    beta_hat :", beta_hat)
print("    RMSE (treino):", rmse41)


### 42. Rolling window 2D com strides  (difícil)
##Usando sliding_window_view, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

I42 = rng.normal(size=(10,10))
patches42 = sliding_window_view(I42, (3,3))
mean42 = patches42.mean(axis=(2,3))
print("42) mean42 shape:", mean42.shape)
print(mean42)



1) v1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2) v2: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3) v3: [0 1 2 3 4 5 6 7 8 9]
4) m4:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
5) idx5 (não zero): [0 1 4]
6) v6: [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
7) I5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
8) m8 (3x3x3):
 [[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]
9) m9 min/max: 0.007362269751005512 0.9691763773477239
10) x10 (z-score): [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
11) a11: [1 2 3] 
    a11_f32: [1. 2. 3.] 
    a11_i64: [1 2 3]
12) a12_clipped: [2 5 5 1 5]
13) 